previews:
  generation: auto_preview

services:
  - type: web
    name: eryze
    runtime: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://eryze.com
