previews:
  generation: automatic

services:
  - type: web
    name: eryze
    runtime: node
    plan: free
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    domains:
      - eryze.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://eryze.com
